# Generated by Django 6.0.2 on 2026-04-27 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('title', models.CharField(max_length=180, verbose_name='عنوان')),
                ('kicker', models.CharField(blank=True, max_length=100, verbose_name='متن کوتاه بالا')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('image', models.ImageField(upload_to='heroes/home/', verbose_name='تصویر اصلی')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='heroes/home/mobile/', verbose_name='تصویر موبایل')),
                ('primary_button_text', models.CharField(blank=True, max_length=60, verbose_name='متن دکمه اصلی')),
                ('primary_button_url', models.CharField(blank=True, max_length=255, verbose_name='لینک دکمه اصلی')),
                ('secondary_button_text', models.CharField(blank=True, max_length=60, verbose_name='متن دکمه دوم')),
                ('secondary_button_url', models.CharField(blank=True, max_length=255, verbose_name='لینک دکمه دوم')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'اسلاید هیروی خانه',
                'verbose_name_plural': 'اسلایدهای هیروی خانه',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('title', models.CharField(max_length=180, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='اسلاگ')),
                ('excerpt', models.CharField(blank=True, max_length=300, verbose_name='خلاصه')),
                ('body', models.TextField(verbose_name='متن')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/covers/', verbose_name='تصویر کاور')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('name', models.CharField(max_length=100, verbose_name='نام زیر\u200cدسته')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='اگر خالی بماند، خودکار از نام ساخته می\u200cشود. برای لینک بهتر، انگلیسی وارد کن؛ مثل bouquet یا box.', max_length=120, verbose_name='اسلاگ')),
                ('section', models.CharField(choices=[('flowers', 'گل\u200cها'), ('bakery', 'بیکری'), ('gifts', 'هدایا'), ('events', 'رویدادها')], db_index=True, max_length=20, verbose_name='بخش اصلی')),
                ('description', models.TextField(blank=True, verbose_name='توضیح کوتاه')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='تصویر زیر\u200cدسته')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال باشد؟')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'زیر\u200cدسته',
                'verbose_name_plural': 'زیر\u200cدسته\u200cها',
                'ordering': ['section', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['section', 'is_active', 'sort_order'], name='main_catego_section_039fc0_idx')],
                'constraints': [models.UniqueConstraint(fields=('section', 'slug'), name='uniq_category_section_slug'), models.UniqueConstraint(fields=('section', 'name'), name='uniq_category_section_name')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('title', models.CharField(max_length=180, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('start_at', models.DateTimeField(verbose_name='شروع')),
                ('end_at', models.DateTimeField(verbose_name='پایان')),
                ('location', models.CharField(max_length=200, verbose_name='مکان')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/covers/', verbose_name='تصویر کاور')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویدادها',
                'ordering': ['start_at', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='event_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('name', models.CharField(max_length=120, verbose_name='نام محصول')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='اگر خالی بماند، خودکار از نام محصول ساخته می\u200cشود.', max_length=160, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('pricing_type', models.CharField(choices=[('fixed', 'قیمت ثابت'), ('inquiry', 'استعلام قیمت')], db_index=True, default='inquiry', max_length=20, verbose_name='نوع قیمت\u200cگذاری')),
                ('price', models.DecimalField(blank=True, decimal_places=0, help_text='فقط عدد وارد کن؛ مثلاً 2500000. اگر قیمت استعلامی باشد، این فیلد خالی می\u200cماند.', max_digits=12, null=True, verbose_name='قیمت به تومان')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='products/covers/', verbose_name='تصویر اصلی')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال باشد؟')),
                ('publish_status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت انتشار')),
                ('stock_status', models.CharField(choices=[('in_stock', 'موجود'), ('out_of_stock', 'ناموجود'), ('preorder', 'پیش\u200cسفارش')], db_index=True, default='in_stock', max_length=20, verbose_name='وضعیت موجودی')),
                ('featured', models.BooleanField(db_index=True, default=False, verbose_name='ویژه باشد؟')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('category', models.ForeignKey(help_text='نوع فیزیکی محصول؛ مثل دسته گل، باکس، استند، کیک تولد، شمع و ...', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='main.category', verbose_name='زیر\u200cدسته')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('full_name', models.CharField(max_length=120, verbose_name='نام')),
                ('mobile', models.CharField(max_length=20, verbose_name='شماره موبایل')),
                ('lead_type', models.CharField(choices=[('flower', 'گل'), ('bakery', 'بیکری'), ('gift', 'هدیه'), ('event', 'رویداد')], max_length=20, verbose_name='نوع درخواست')),
                ('delivery_window', models.CharField(choices=[('today', 'امروز'), ('tomorrow', 'فردا'), ('pick_date', 'تاریخ انتخابی')], max_length=20, verbose_name='بازه تحویل')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انتخابی')),
                ('event_location', models.CharField(blank=True, max_length=180, verbose_name='مکان رویداد')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('source_page', models.CharField(blank=True, max_length=255, verbose_name='صفحه مبدا')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_requests', to='main.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره',
                'verbose_name_plural': 'درخواست\u200cهای مشاوره',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BakeryItem',
            fields=[
            ],
            options={
                'verbose_name': 'محصول بیکری',
                'verbose_name_plural': 'محصولات بیکری',
                'ordering': ['sort_order', '-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
            ],
            options={
                'verbose_name': 'محصول گل',
                'verbose_name_plural': 'محصولات گل',
                'ordering': ['sort_order', '-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='GiftItem',
            fields=[
            ],
            options={
                'verbose_name': 'هدیه',
                'verbose_name_plural': 'هدایا',
                'ordering': ['sort_order', '-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='SiteHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('title', models.CharField(max_length=180, verbose_name='عنوان')),
                ('kicker', models.CharField(blank=True, max_length=100, verbose_name='متن کوتاه بالا')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('image', models.ImageField(upload_to='heroes/pages/', verbose_name='تصویر اصلی')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='heroes/pages/mobile/', verbose_name='تصویر موبایل')),
                ('target_page', models.CharField(choices=[('flowers', 'گل\u200cها'), ('bakery', 'بیکری'), ('gifts', 'هدایا'), ('events', 'رویدادها'), ('occasions', 'مناسبت\u200cها'), ('contact', 'تماس با ما'), ('visit', 'بازدید حضوری'), ('faq', 'سوالات پرتکرار'), ('blog', 'بلاگ'), ('mashhad', 'سفارش در مشهد'), ('subcategory', 'زیر\u200cدسته'), ('item', 'صفحه محصول')], max_length=30, verbose_name='صفحه هدف')),
                ('target_slug', models.CharField(blank=True, help_text='برای زیر\u200cدسته یا صفحه خاص، اسلاگ را وارد کن. مثال: bouquet', max_length=120, verbose_name='اسلاگ هدف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'هیروی صفحه',
                'verbose_name_plural': 'هیروهای صفحات',
                'ordering': ['target_page', 'sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('target_page', 'target_slug', 'sort_order'), name='uniq_sitehero_target_slug_sort')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام برچسب')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='اگر خالی بماند، خودکار ساخته می\u200cشود. برای لینک بهتر، انگلیسی وارد کن؛ مثل birthday یا romantic.', max_length=80, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیح کوتاه')),
                ('cover_image', models.ImageField(blank=True, help_text='برای کارت\u200cهای مناسبتی مثل تولد، تسلیت، عاشقانه و ...', null=True, upload_to='tags/', verbose_name='تصویر کارت مناسبتی')),
                ('is_occasion', models.BooleanField(db_index=True, default=True, verbose_name='در کارت\u200cهای مناسبتی نمایش داده شود؟')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال باشد؟')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_occasion', 'is_active', 'sort_order'], name='main_tag_is_occa_16ce28_idx')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='مناسبت یا کاربرد محصول؛ مثل تولد، تسلیت، عذرخواهی، خاص، عاشقانه.', related_name='products', to='main.tag', verbose_name='برچسب\u200cها'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=150, verbose_name='متن جایگزین')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='main.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'ordering': ['ordering', 'id'],
                'indexes': [models.Index(fields=['product', 'ordering'], name='main_produc_product_9452e5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active', 'publish_status'], name='main_produc_categor_c92952_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['featured', 'sort_order'], name='main_produc_feature_bebd6e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sort_order', '-created_at'], name='main_produc_sort_or_62d747_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['pricing_type', 'stock_status'], name='main_produc_pricing_972eee_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gte', 0), _connector='OR'), name='product_price_is_positive_or_null'),
        ),
    ]
