# Generated by Django 6.0.2 on 2026-02-23 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='flowercovers/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='flower',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='tarikhe sabt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flower',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='tarikhe berooz resani'),
        ),
    ]
