# Generated by Django 6.0.2 on 2026-02-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_flower_cover_flower_created_at_flower_update_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flower',
            options={'ordering': ['-created_at'], 'verbose_name': 'گل', 'verbose_name_plural': 'گل\u200cها'},
        ),
        migrations.RemoveField(
            model_name='flower',
            name='update_at',
        ),
        migrations.AddField(
            model_name='flower',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='flowercovers/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
    ]
