# Generated by Django 6.0.2 on 2026-02-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_flower_options_remove_flower_update_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, null=True, verbose_name='اسلاگ'),
        ),
    ]
