# Generated by Django 6.0.2 on 2026-02-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_flower_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, unique=True, verbose_name='اسلاگ'),
        ),
    ]
