# Generated by Django 6.0.2 on 2026-05-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_product_code_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, editable=False, max_length=40, unique=True, verbose_name='کد محصول'),
        ),
    ]
