# Generated by Django 6.0.2 on 2026-04-21 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_category_options_category_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricing_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('inquiry', 'Call / Inquiry')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='publish_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='main.category'),
            preserve_default=False,
        ),
    ]
