# Generated by Django 6.0.2 on 2026-04-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_product_pricing_type_product_publish_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_cover',
        ),
    ]
