# Generated by Django 6.0.2 on 2026-04-21 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_productimage_is_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_requests', to='main.product'),
        ),
    ]
