# Generated by Django 6.0.2 on 2026-04-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_leadrequest_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('kicker', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='heroes/home/')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='heroes/home/mobile/')),
                ('primary_button_text', models.CharField(blank=True, max_length=60)),
                ('primary_button_url', models.CharField(blank=True, max_length=255)),
                ('secondary_button_text', models.CharField(blank=True, max_length=60)),
                ('secondary_button_url', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'اسلاید هیروی خانه',
                'verbose_name_plural': 'اسلایدهای هیروی خانه',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('kicker', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='heroes/pages/')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='heroes/pages/mobile/')),
                ('target_page', models.CharField(choices=[('flowers', 'گل\u200cها'), ('bakery', 'بیکری'), ('gifts', 'هدایا'), ('events', 'رویدادها'), ('contact', 'تماس با ما'), ('visit', 'بازدید حضوری'), ('faq', 'سوالات پرتکرار'), ('blog', 'بلاگ'), ('mashhad', 'سفارش در مشهد'), ('subcategory', 'زیر\u200cدسته'), ('item', 'صفحه محصول')], max_length=30)),
                ('target_slug', models.CharField(blank=True, help_text='برای زیر\u200cدسته یا صفحه خاص، اسلاگ را وارد کنید. مثال: bouquet', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'هیروی صفحه',
                'verbose_name_plural': 'هیروهای صفحات',
                'ordering': ['target_page', 'sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('target_page', 'target_slug', 'sort_order'), name='uniq_sitehero_target_slug_sort')],
            },
        ),
    ]
