# Generated by Django 6.0.2 on 2026-04-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_homeheroslide_sitehero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_type', 'sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('occasion', 'Occasion'), ('price', 'Price Level'), ('vibe', 'Vibe')], db_index=True, default='occasion', max_length=20),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('tag_type', 'name'), name='uniq_tag_type_name'),
        ),
    ]
