# Generated by Django 6.0.2 on 2026-02-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام محصول')),
                ('pack_type', models.CharField(choices=[('box', 'باکس'), ('bouquet', 'دسته گل'), ('basket', 'سبد'), ('stem', 'شاخه'), ('stand', 'پایه')], max_length=20, verbose_name='نوع بسته\u200cبندی')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
                ('about', models.TextField(blank=True, max_length=200, null=True, verbose_name='توضیحات')),
                ('category', models.CharField(choices=[('birthday', 'تولد'), ('daily', 'روزمره'), ('love', 'عاشقانه'), ('gift', 'هدیه')], max_length=20, verbose_name='دسته\u200cبندی')),
            ],
        ),
    ]
