# Generated by Django 6.0.2 on 2026-02-25

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def forwards_migrate_products(apps, schema_editor):
    Product = apps.get_model("main", "Product")
    Category = apps.get_model("main", "Category")

    category_map = {
        "birthday": "Birthday",
        "daily": "Daily",
        "love": "Love",
        "gift": "Gift",
    }

    for product in Product.objects.all().iterator():
        legacy_code = (product.legacy_category or "").strip().lower()
        category_name = category_map.get(legacy_code, legacy_code.title() or "Uncategorized")
        category_slug = slugify(legacy_code or category_name.lower()) or "uncategorized"

        category, _ = Category.objects.get_or_create(
            section="flowers",
            slug=category_slug,
            defaults={"name": category_name},
        )

        product.category_id = category.id
        product.save(update_fields=["category"])

    schema_editor.execute(
        """
        INSERT INTO main_flower (product_ptr_id, pack_type)
        SELECT
            p.id,
            CASE
                WHEN p.legacy_pack_type IN ('box', 'bouquet', 'basket', 'stem', 'stand')
                THEN p.legacy_pack_type
                ELSE 'bouquet'
            END
        FROM main_product p
        WHERE NOT EXISTS (
            SELECT 1 FROM main_flower f WHERE f.product_ptr_id = p.id
        )
        """
    )


def reverse_noop(apps, schema_editor):
    # Irreversible data migration after schema normalization.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_flower_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120)),
                (
                    "section",
                    models.CharField(
                        choices=[("flowers", "Flowers"), ("bakery", "Bakery"), ("gifts", "Gifts")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["section", "name"],
                "constraints": [
                    models.UniqueConstraint(fields=("section", "slug"), name="uniq_category_section_slug")
                ],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(max_length=70, unique=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.RenameModel(
            old_name="Flower",
            new_name="Product",
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["sort_order", "-created_at"]},
        ),
        migrations.RenameField(
            model_name="product",
            old_name="about",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="cover",
            new_name="cover_image",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="category",
            new_name="legacy_category",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="pack_type",
            new_name="legacy_pack_type",
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True, max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="products/covers/"),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="main.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_status",
            field=models.CharField(
                choices=[
                    ("in_stock", "In stock"),
                    ("out_of_stock", "Out of stock"),
                    ("preorder", "Preorder"),
                ],
                default="in_stock",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BakeryItem",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.product",
                    ),
                ),
                ("size_or_weight", models.CharField(blank=True, max_length=60)),
                ("is_vegan", models.BooleanField(default=False)),
            ],
            bases=("main.product",),
            options={"ordering": ["sort_order", "-created_at"]},
        ),
        migrations.CreateModel(
            name="Flower",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.product",
                    ),
                ),
                (
                    "pack_type",
                    models.CharField(
                        choices=[
                            ("box", "Box"),
                            ("bouquet", "Bouquet"),
                            ("basket", "Basket"),
                            ("stem", "Stem"),
                            ("stand", "Stand"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            bases=("main.product",),
            options={"ordering": ["sort_order", "-created_at"]},
        ),
        migrations.CreateModel(
            name="GiftItem",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.product",
                    ),
                ),
                ("material", models.CharField(blank=True, max_length=100)),
                ("handmade", models.BooleanField(default=False)),
            ],
            bases=("main.product",),
            options={"ordering": ["sort_order", "-created_at"]},
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField()),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("location", models.CharField(max_length=200)),
                ("cover_image", models.ImageField(blank=True, null=True, upload_to="events/covers/")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["start_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("excerpt", models.CharField(blank=True, max_length=300)),
                ("body", models.TextField()),
                ("cover_image", models.ImageField(blank=True, null=True, upload_to="news/covers/")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["-published_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="products/gallery/")),
                ("alt_text", models.CharField(blank=True, max_length=150)),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("is_cover", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="main.product",
                    ),
                ),
            ],
            options={"ordering": ["ordering", "id"]},
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="products", to="main.tag"),
        ),
        migrations.RunPython(forwards_migrate_products, reverse_noop),
        migrations.RemoveField(
            model_name="product",
            name="legacy_category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="legacy_pack_type",
        ),
    ]
