# Generated by Django 6.0.2 on 2026-02-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_created_at_alter_product_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=20)),
                ('lead_type', models.CharField(choices=[('flower', 'گل'), ('bakery', 'بیکری'), ('gift', 'هدیه'), ('event', 'رویداد')], max_length=20)),
                ('delivery_window', models.CharField(choices=[('today', 'امروز'), ('tomorrow', 'فردا'), ('pick_date', 'تاریخ انتخابی')], max_length=20)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('event_location', models.CharField(blank=True, max_length=180)),
                ('note', models.TextField(blank=True)),
                ('source_page', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
    ]
