# Generated by Django 6.0.2 on 2026-02-26 01:09

from django.db import migrations


def create_flower_subcategories(apps, schema_editor):
    Category = apps.get_model("main", "Category")
    entries = [
        ("bouquet", "دسته‌گل"),
        ("box", "باکس گل"),
        ("stand", "استند و تاج"),
        ("plant", "گیاه"),
    ]
    for slug, name in entries:
        Category.objects.get_or_create(
            section="flowers",
            slug=slug,
            defaults={"name": name},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_leadrequest_alter_product_slug'),
    ]

    operations = [
        migrations.RunPython(create_flower_subcategories, noop_reverse),
    ]
